services:
  db:
    image: postgres:16.4
    container_name: postgres_db
    env_file:
      - .env
    networks:
      - etl_network
    ports:
      - "4500:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 5s

  etl_service:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./Transformed:/app/Transformed
      - ./etl:/app/etl
    depends_on:
      db:
        condition: service_healthy

    networks:
      - etl_network

networks:
  etl_network: